### PR TITLE
Swift 5 layout

### PR DESCRIPTION
**Pull request by yaroslav-zhurakovskiy**
Update concerning this issue https://github.com/fulldecent/YTBarButtonItemWithBadge/issues/2

I will check travis ci and cocoapods later

### CODE REVIEW

**Comment by fulldecent** [comment]
Please use // swift-tools-version:5.1 as per
https://github.com/fulldecent/swift5-module-template

Also please bring in relevant README sections regarding installation from https://github.com/fulldecent/swift5-module-template

**Comment by yaroslav-zhurakovskiy** [comment]
I removed Carthage from README.md.

**Review by fulldecent — APPROVED** [review]

**Comment by fulldecent** [comment]
Looks great, thank you. Can you please add an example app https://github.com/fulldecent/YTBarButtonItemWithBadge/issues/4

**Comment by yaroslav-zhurakovskiy** [comment]
Sure

**Pull request merged**
